
calendarList = {
    'PA':  {'active': True,  
            'type': 'Google', 
            'appName':'Calendar Sync', 
            'secrets':'pete_client_secret.json', 
            'creds_file':'pete-credentials.json', 
            'publishDetails': '', 
            'email': 'pete@anewalt.com'},
    'MOV': {'active': False, 
            'type': 'Google', 
            'appName':'MOV Calendar Sync', 
            'secrets':'mov_client_secret.json', 
            'creds_file':'mov-credentials.json', 
            'publishDetails': 'PA', 
            'email': 'pete@mov-ology.com'},
    'GC':  {'active': False, 
            'type': 'Google', 
            'appName':'Calendar Sync', 
            'secrets':'gc_client_secret.json', 
            'creds_file':'gc-credentials.json', 
            'publishDetails': 'PA,MOV', 
            'email': 'pete@geocommerce.com'},
    'UL':  {'active': False, 
            'type': 'Outlook', 
            'appName':'Calendar Sync', 
            'creds_file': 'ul-credentials.txt', 
            'publishDetails': 'PA,UL2', 
            'email': 'pete@uledger.co'},
    'UL2': {'active': True,  
            'type': 'Google', 
            'appName':'Calendar Sync', 
            'secrets': 'ul_client_secret.json', 
            'creds_file':'ul-credentials.json',
            'publishDetails': 'PA,UL', 
            'email': 'pete@uledger.co'}
    }
